services:

  mysql:
    image: mysql:8
    container_name: attendance_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: attendance_app
    restart: always

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8000:8000"

    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: attendance
      FINGERPRINT_TYPE: SIMULATE

volumes:
  mysql_data:
